# Generated by Django 3.0.7 on 2020-07-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='help_image',
        ),
    ]
