# Generated by Django 3.0.7 on 2020-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_help_help_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='help_image',
            field=models.ImageField(blank=True, null=True, upload_to='help//%y/%m'),
        ),
    ]
