# Generated by Django 3.0.7 on 2020-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70)),
                ('help_text', models.CharField(max_length=110)),
                ('help_image', models.ImageField(upload_to='help//%y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
