# Generated by Django 3.0.7 on 2020-06-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0002_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='help_image',
            field=models.ImageField(blank=True, null=True, upload_to='help//%y/%m'),
        ),
    ]
