# Generated by Django 3.0.7 on 2020-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0003_auto_20200607_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'ordering': ['-id']},
        ),
    ]
