# Generated by Django 3.0.7 on 2020-06-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0005_auto_20200614_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Location',
        ),
    ]
