# Generated by Django 3.0.7 on 2020-06-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0006_auto_20200616_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagion',
            name='date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contagion',
            name='is_publish',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
