# Generated by Django 3.0.7 on 2020-06-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0007_auto_20200616_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
    ]
