# Generated by Django 3.0.7 on 2020-06-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0008_remove_location_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
    ]
