# Generated by Django 3.0.7 on 2020-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0009_remove_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('Governmental', 'Governmental'), ('Private', 'Private')], default='Governmental', max_length=20),
        ),
    ]
