# Generated by Django 3.0.7 on 2020-06-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0010_hospital_hospital_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
