# Generated by Django 3.0.7 on 2020-06-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='designation_year',
            new_name='job_year',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='doctor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TimeField()),
                ('phone_number', models.IntegerField(default=0)),
                ('profile_photo', models.ImageField(upload_to='patient')),
                ('age', models.ImageField(upload_to='', verbose_name=0)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=70, null=True)),
                ('reference_phone_number', models.ImageField(default=0, upload_to='')),
                ('gender', models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE'), ('Other', 'OTHER')], default='Male', max_length=10)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PatientProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
