# Generated by Django 3.0.7 on 2020-07-09 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
