# Generated by Django 3.0.7 on 2020-07-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200709_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='location',
            new_name='address',
        ),
    ]
