# Generated by Django 3.0.7 on 2020-06-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20200621_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_name', models.CharField(max_length=120)),
                ('machinery_name', models.CharField(blank=True, max_length=150, null=True)),
                ('total_machinery', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'doctor'), (2, 'nurse'), (3, 'laboratories'), (4, 'accountant'), (5, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=1)),
                ('discount_price', models.IntegerField(default=0)),
                ('laboratories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_laboratories', to='hospital.Laboratories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialist',
            new_name='specialization',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(max_length=120)),
                ('patient_name', models.CharField(blank=True, max_length=70, null=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_patient_name', to='hospital.Patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_service', to='hospital.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=90)),
                ('phn_number', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('Department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointment', to='hospital.Department')),
                ('schedules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_schedules', to='hospital.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='roles',
            field=models.ManyToManyField(to='hospital.Role'),
        ),
    ]
