# Generated by Django 3.0.7 on 2020-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20200621_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(max_length=70),
        ),
    ]
