# Generated by Django 3.0.7 on 2020-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20200710_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availability',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.ManyToManyField(related_name='doctor_availability', to='hospital.Availability'),
        ),
    ]
